employees_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes employees
  resources :employees

  # Routes leave days
  get '/all_leavedays', to: 'employees#all_leavedays'
  post '/all_leavedays', to: 'employees#update_leavedays'
  resources :leavedays

  # Routes projects
  resources :projects

  # Routes ots
  resources :ots

  # Routes members
  resources :members 

  root 'employees#index'

end

employees_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees</title>
    
    <%= favicon_link_tag 'users.png' %>
    <!-- <link rel="shortcut icon" href="users.png"> -->

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Main-top -->
    <div class="main-top">
        <i class="fa fa-user-o" aria-hidden="true" style="padding-left: 15px;"></i> 
        EMPLOYEE MANAGE
        <div class="btn-group"  style="float:right;margin: 15px 20px 0px 0px;">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right">
                <li style="height: 15px;">
                    <a href='#'>
                        <i class="fa fa-user"></i>
                        My profile
                    </a>
                </li>
                <li style="height: 15px; margin-top: 10px;">
                    <a href='#'>
                        <i class="fa fa-key"></i>
                        Change password
                    </a>
                </li>
                <li style="height: 15px; margin: 10px 0px 10px 0px;">
                    <a href='#'>
                        <i class="fa fa-sign-out"></i>
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!-- div này dùng để sửa lỗi cho div trên khi dùng positive:fixed;-->
    <div style="width: 100%; height: 60px;"></div>

    <div class="main-content">
        <!-- Sidebar -->
        <div class="nav-side-menu">
            <div class="menu-list">
                <ul id="menu-content" class="menu-content collapse out">
                    <!--Cần giải quyết: khi trang được load thì mới active li dẫn đến trang đó???-->
                    <li>
                        <i class="fa fa-dashboard"></i>
                        Dashboard
                    </li>

                    <li data-toggle="collapse" data-target="#employees" class="collapsed">
                        <i class="fa fa-user"></i>
                        Employees manage
                        <span class="arrow"></span>
                    </li>
                    <ul class="sub-menu collapse" id="employees">
                        <li>
                            <%= link_to 'List of employees', employees_path %>
                        </li>
                        <li>
                            <%= link_to 'Add new employee', new_employee_path %>
                        </li>
                    </ul>

                    <li>
                        <i class="fa fa-money"></i>
                        <%= link_to 'OT manage', ots_path %>
                    </li>

                    <li data-toggle="collapse" data-target="#leavedays" class="collapsed">
                        <i class="fa fa-calendar"></i>
                        Leave days manage
                        <span class="arrow"></span>
                    </li>
                    <ul class="sub-menu collapse" id="leavedays">
                        <li>
                            <%= link_to 'Monthly manage', leavedays_path %>
                        </li>
                        <li>
                            <%= link_to 'All manage', all_leavedays_path %>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#projects" class="collapsed">
                        <i class="fa fa-suitcase"></i>
                        Projects manage
                        <span class="arrow"></span>
                    </li>
                    <ul class="sub-menu collapse" id="projects">
                        <li>
                            <%= link_to 'List of projects', projects_path %>
                        </li>
                        <li>
                            <%= link_to 'Add new project', new_project_path %>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#members" class="collapsed">
                        <i class="fa fa-group"></i>
                        Members of project
                        <span class="arrow"></span>
                    </li>
                    <ul class="sub-menu collapse" id="members">
                        <li>
                            <%= link_to 'List of members', members_path %>
                        </li>
                        <li>
                            <%= link_to 'Add new member', new_member_path %>
                        </li>
                    </ul>
                </ul>
            </div>
        </div>

        <div class="main-content-body">                 
            <!-- Content -->
            <%= yield %>
        </div>
    </div>

    
  </body>
</html>