employees_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes employees
  resources :employees

  # Routes leave days
  get '/all_leavedays', to: 'employees#all_leavedays'
  post '/all_leavedays', to: 'employees#update_leavedays'
  resources :leavedays

  # Routes projects
  resources :projects

  # Routes ots
  resources :ots

  # Routes members
  resources :members 

  root 'employees#index'

end

employees_management/app/models/member.rb
class Member < ApplicationRecord
  belongs_to :employee
  belongs_to :project
end

employees_management/app/controllers/members_controller.rb
class MembersController < ApplicationController
	def index
		@demos = Member.all.where(del_flag: 0)

		@projects = Project.select('id', 'project_name', 'project_status').where(del_flag: 0)		
		@members = Member.select('project_id', 'employees.fullname', 'user_type', 'join_status', 'employee_id').joins('INNER JOIN employees ON members.employee_id = employees.id').where('members.del_flag = ?', 0)
		
	end

	def show
		@member = Member.find(params[:id])
	end

	def new
		@member = Member.new
	end

	def create
		@member = Member.new(member_params)
		if (@member.save)
			flash[:success] = "Insert success!"
			redirect_to members_path
		else
			render 'new'
		end
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update
		@member = Member.find(params[:id])
		if (@member.update(member_params))
			flash[:success] = 'Edit success!'
			redirect_to members_path
		else
			render 'edit'
		end
	end

	def destroy
		if Member.update(params[:id], :del_flag => 1)
			flash[:success] = "Delete success!"
		end
		redirect_to @members_path
	end

	private def member_params
		params.require(:member).permit(:project_id, :employee_id, :user_type, :join_status,:del_flag)
	end
end

employees_management/app/helpers/members_helper.rb
module MembersHelper
end

employees_management/app/views/members/edit.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-users"></i> Members of project</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">Edit member of project</span></li>
</ol>
<div class="panel panel-info">
	<div class="panel-heading">Edit member of project</div>
	<div class="panel-body">
		<%= form_for @member do |f| %>
			<!-- Display errors -->
			<% if @member.errors.any? %>
				<div class="row">
					<div class="col-md-12">
						<div class="alert alert-danger">
							<% @member.errors.full_messages.each do |msg| %>
									&#9679; <%= msg %> <br>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :project_id, 'Project: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :project_id, Project.where(del_flag: 0).collect { |p| [p.project_name, p.id] }, {}, :class => 'form-control', disabled: true %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :employee_id, 'Member: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :employee_id, Employee.joins('INNER JOIN members ON members.employee_id = employees.id').where('employees.del_flag = ? AND members.project_id = ?', 0, params[:id]).collect { |e| [e.fullname, e.id] }, { include_blank: '--- Select member ---' }, :class => 'form-control' %>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :join_status, 'Status: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :join_status, [['--- Select status ---', ''], 'Joining', 'Exited'], {}, :class => 'form-control' %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :user_type, 'Level: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :user_type, [['--- Select user type ---', ''], ['Leader', 0], ['Member', 1]], {}, :class => 'form-control' %>
				</div>
			</div>

			<%= f.hidden_field :del_flag, :value => '0' %>

			<div class="row">
				<div class="form-group text-center">
					<%= button_tag "Reset", type: 'reset', id: 'reset_member', name: 'reset', class: 'btn btn-primary' %>
					<%= f.submit 'Save', class: 'btn btn-danger' %>
				</div>
			</div>

		<% end %>
	</div>
</div>

employees_management/app/views/members/index.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-users"></i> Members of project</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">List of members</span></li>
</ol>

<!-- Display notification -->
<% flash.each do |type, message| %>
	<%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= message %>
	<% end %>
<% end %>

<div class="panel panel-info">
	<div class="panel-heading">List of members</div>
	<div class="panel-body">
		<%= link_to '<i class="fa fa-refresh"></i> Reload'.html_safe, members_path, :class => "btn btn-default" %>
		<div class="table-responsive">			
			<table class="table table-bordered table-hover" style="margin-top: 15px; font-size: 11px;">
				<thead style="background: #53585a; color: #fff;">
					<th class="text-center">No.</th>
					<th>Project</th>
					<th>Leader</th>
					<th>Members</th>
					<th>Status</th>
					<th class="text-center">Detail</th>
					<th class="text-center">Edit</th>
				</thead>
				<tbody>

					<%
					list = {}

					@projects.each do |p|
						id = p.id
						project_name = p.project_name
						project_status = p.project_status
						list[id] = {'id' => id, 'project_name' => project_name, 'project_status' => project_status, 'member' => {}}
					end 

					maxMember = 1

					@members.each do |m|
						memberName = m.fullname
						memberStatus = m.join_status
						memberType = m.user_type.to_i
						id = m.project_id
						memberId = m.employee_id
						if list.has_key?(id)
							if memberType == 0
								list[id]['leader'] = memberName
							else
								maxMember = (maxMember < memberId) ? memberId : maxMember
								list[id]['member'].merge!({memberId => memberName+' - '+memberStatus})
							end
						end
					end


					%>

					<% if list.nil? %>
						<td colspan="5" class="text-center"><span style="color: red;"><i class="fa fa-exclamation-triangle"></i> Not data</span></td>
					<% else 
						no = 1
						list.each_value do |member| %>
							<tr>
								<td class="text-center"><%= no %></td>
								<td><%= member['project_name'] %></td>
								<td><%= member['leader'] %></td>
								<td>
									<% for i in 1..maxMember
										if member['member'].has_key?(i) %>
												&#9679; <%= member['member'][i] %> <br>
										<% end 
									end %>		
								</td>
								<td><%= member['project_status'] %></td>
								<td class="text-center"><%= link_to '<i class="fa fa-info-circle"></i>'.html_safe, project_path(member['id']), :class => 'btn btn-sm btn-success' %></td>
								<td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_member_path(member['id']), :class => 'btn btn-sm btn-primary' %></td>
							</tr>
						<% no += 1
						end
					end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

employees_management/app/views/members/new.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-users"></i> Members of project</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">Edit member of project</span></li>
</ol>
<div class="panel panel-info">
	<div class="panel-heading">Edit member of project</div>
	<div class="panel-body">
		<%= form_for :member, url: members_path do |f| %>
			<!-- Display errors -->
			<% if @member.errors.any? %>
				<div class="row">
					<div class="col-md-12">
						<div class="alert alert-danger">
							<% @member.errors.full_messages.each do |msg| %>
									&#9679; <%= msg %> <br>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :project_id, 'Project: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :project_id, Project.where(del_flag: 0).collect { |p| [p.project_name, p.id] }, { include_blank: '--- Select project --- ' }, :class => 'form-control' %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :employee_id, 'Member: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :employee_id, Employee.where(del_flag: 0).collect { |e| [e.fullname, e.id] }, { include_blank: '--- Select member ---' }, :class => 'form-control' %>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :join_status, 'Status: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :join_status, [['--- Select status ---', ''], 'Joining', 'Exited'], {}, :class => 'form-control' %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :user_type, 'Level: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :user_type, [['--- Select user type ---', ''], ['Leader', 0], ['Member', 1]], {}, :class => 'form-control' %>
				</div>
			</div>

			<%= f.hidden_field :del_flag, :value => '0' %>

			<div class="row">
				<div class="form-group text-center">
					<%= button_tag "Reset", type: 'reset', id: 'reset_member', name: 'reset', class: 'btn btn-primary' %>
					<%= f.submit 'Save', class: 'btn btn-danger' %>
				</div>
			</div>

		<% end %>
	</div>
</div>