employees_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes employees
  resources :employees

  # Routes leave days
  get '/all_leavedays', to: 'employees#all_leavedays'
  post '/all_leavedays', to: 'employees#update_leavedays'
  resources :leavedays

  # Routes projects
  resources :projects

  # Routes ots
  resources :ots

  # Routes members
  resources :members 

  root 'employees#index'

end

employees_management/app/models/project.rb
class Project < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :ots
	has_many :members
end

employees_management/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
    	@projects = if params[:project_name]
            # Project.select('projects.id', 'projects.project_name', 'projects.project_lang', 'projects.project_status', 'projects.start_datetime', 'projects.end_datetime', 'employees.fullname', 'members.user_type').joins("INNER JOIN members ON projects.id = members.project_id INNER JOIN employees ON employees.id = members.employee_id").where('projects.project_name LIKE ? AND projects.del_flag = ? AND members.user_type = ?', "%#{params[:project_name]}%", 0, 0).paginate(:page => params[:page], :per_page => 10).order("projects.id DESC")
            Project.select('id', 'project_name', 'project_status', 'project_lang', 'start_datetime', 'end_datetime').where('projects.project_name LIKE ? AND del_flag = ? ', "%#{params[:project_name]}%", 0).paginate(:page => params[:page], :per_page => 10).order("id DESC")
    	else
            # Project.select('projects.id', 'projects.project_name', 'projects.project_lang', 'projects.project_status', 'projects.start_datetime', 'projects.end_datetime', 'employees.fullname', 'members.user_type').joins("INNER JOIN members ON projects.id = members.project_id INNER JOIN employees ON employees.id = members.employee_id").where('projects.del_flag = ? AND members.user_type = ?', 0, 0).paginate(:page => params[:page], :per_page => 10).order("projects.id DESC")
            Project.select('id', 'project_name', 'project_status', 'project_lang', 'start_datetime', 'end_datetime').where(del_flag: 0).paginate(:page => params[:page], :per_page => 10).order("id DESC")
    	end
    end

    def new
    	@project = Project.new
    	@users = Employee.select('fullname', 'id').where(del_flag: 0)
    end

    def show
    	@project = Project.find(params[:id])
        @leader = Employee.select('fullname').joins('INNER JOIN members ON employees.id = members.employee_id').where('members.project_id = ? AND members.del_flag = ? AND members.user_type = ?', params[:id], 0, 0)
        @members = Employee.select('fullname').joins('INNER JOIN members ON employees.id = members.employee_id').where('members.project_id = ? AND members.del_flag = ? AND members.user_type = ?', params[:id], 0, 1)
    end

    def create
    	@project = Project.new(project_params)

    	if @project.save
    		flash[:success] = "Insert success!"
    		redirect_to projects_path
    	else
    		render 'new'
    	end
    end

    def edit
    	@project = Project.find(params[:id])
    end

    def update
    	@project = Project.find(params[:id])
    	if @project.update(project_params)
    		flash[:success] = 'Edit success!'
    		redirect_to projects_path
    	else
    		render 'edit'
    	end
    end

    def destroy
    	# @project = Project.find(params[:id])
    	if (Project.update(params[:id], :del_flag => 1))
    		flash[:success] = "Delete success!"
    	end
    	redirect_to projects_path
    end

    private def project_params
        params.require(:project).permit(:project_name, :project_status, :start_datetime, :end_datetime, :project_lang, :description, :del_flag)
    end
end

employees_management/app/helpers/projects_helper.rb
module ProjectsHelper
end

employees_management/app/views/projects/edit.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Projects manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">Edit information project</span></li>
</ol>

<div class="panel panel-info">
	<div class="panel-heading">Edit information project</div>
	<div class="panel-body">
		<%= form_for @project do |f| %>
			<!-- Display errors -->
			<% if @project.errors.any? %>
				<div class="row">
					<div class="col-md-12">
						<div class="alert alert-danger">
							<% @project.errors.full_messages.each do |msg| %>
									&#9679; <%= msg %> <br>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :project_name, 'Project name: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.text_field :project_name, :class => "form-control", :placeholder => "Project name" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :project_status, 'Project status: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :project_status, [['--- Select status ---', ''], 'Running', 'Maintenance', 'Received', 'Closed'], {}, :class => "form-control" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :project_lang, 'Language development: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.text_field :project_lang, :class => "form-control", :placeholder => "Project language" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :start_datetime, 'Start datetime: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.date_field :start_datetime, :class => "form-control" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :end_datetime, 'End datetime:' %>
					<%= f.date_field :end_datetime, :class => "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :description, 'Description:' %>
					<%= f.text_area :description, :rows => 8, :class => "form-control", :placeholder => "Description" %>
				</div>
			</div>

			<%= f.hidden_field :del_flag, :value => '0' %>

			<div class="row">
				<div class="form-group text-center">
					<%= f.submit 'Save', class: 'btn btn-danger' %>
					<%= submit_tag('Reset', {:name => 'reset', :type => 'reset', :id => 'reset_new_project', :class => 'btn btn-default'}) %>
				</div>
			</div>
		<% end %>
	</div>
</div>

employees_management/app/views/projects/index.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-suitcase"></i> Projects manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">List of projects</span></li>
</ol>

<!-- Display notification -->
<% flash.each do |type, message| %>
	<%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= message %>
	<% end %>
<% end %> 

<div class="panel panel-info">
	<div class="panel-heading">Search project</div>
	<div class="panel-body">
		<%= form_tag(projects_path, method: :get) do %>
			<div class="row">
				<div class="form-group col-md-12">
					<%= label_tag :project_name, "Tên dự án:" %>
					<%= text_field_tag :project_name, params[:project_name], class: "form-control", placeholder: "Project name" %>
				</div>
			</div>
			<div class="row" style="margin-top: 15px;">
				<div class="form-group text-center">
					<%= submit_tag("Reset", {:type => "reset", :name => "reset", :id => "reset_project", :class => "btn btn-primary"}) %>
					<%= submit_tag "Search", class: "btn btn-danger" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

<div class="panel panel-info">
	<div class="panel-heading">List of projects</div>
	<div class="panel-body">
		<%= link_to '<i class="fa fa-refresh"></i> Reload'.html_safe, projects_path, :class => "btn btn-default" %>
		<div class="table-responsive">			
			<table class="table table-bordered table-hover" style="margin-top: 15px; font-size: 11px;">
				<thead style="background: #53585a; color: #fff;">
					<th class="text-center">No.</th>
					<th>Project name</th>
					<!-- <th>Leader</th> -->
					<th>Project status</th>
					<th>Language</th>
					<th>Start datetime</th>
					<th>End datetime</th>
					<th>Detail</th>
					<th class="text-center">Edit</th>
					<th class="text-center">Delete</th>
				</thead>
				<tbody>
					<% if @projects.empty? %>
						<tr><td colspan="9" class="text-center"><span style="color: red;"><i class="fa fa-exclamation-triangle"></i> Not data</span></td></tr>
					<% else %>
						<% i = 1 %>
						<% @projects.each do |project| %>
							<tr>
								<td class="text-center"><%= i %></td>
								<td><%= project.project_name %></td>
								<!-- <td><%# project.fullname %></td> -->
								<td><%= project.project_status %></td>
								<td><%= project.project_lang %></td>
								<td><%= project.start_datetime %></td>
								<td><%= project.end_datetime %></td>
								<td class="text-center"><%= link_to '<i class="fa fa-info-circle"></i>'.html_safe, project_path(project.id), :class => "btn btn-sm btn-info" %></td>
								<td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_project_path(project.id), :class => "btn btn-sm btn-primary" %></td>
								<td class="text-center"><%= link_to '<i class="fa fa-trash"></i>'.html_safe, project_path(project.id), method: :delete, :data => { confirm: "Are you sure?" }, :class => "btn btn-sm btn-danger" %></td>
							</tr>
							<% i += 1 %>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>

		<!-- Pagination -->
		<%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
	</div>
</div>

employees_management/app/views/projects/new.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Projects manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">Add new project</span></li>
</ol>

<div class="panel panel-info">
	<div class="panel-heading">Add new project</div>
	<div class="panel-body">
		<%= form_for :project, url: projects_path do |f| %>
			<!-- Display errors -->
			<% if @project.errors.any? %>
				<div class="row">
					<div class="col-md-12">
						<div class="alert alert-danger">
							<% @project.errors.full_messages.each do |msg| %>
									&#9679; <%= msg %> <br>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :project_name, 'Project name: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.text_field :project_name, :class => "form-control", :placeholder => "Project name" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :project_status, 'Project Status: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :project_status, [['--- Select status ---', ''], 'Running', 'Maintenance', 'Received', 'Closed'], {}, :class => "form-control" %>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :project_lang, 'Language development: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.text_field :project_lang, :class => "form-control", :placeholder => "Project language" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :start_datetime, 'Start datetime: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.date_field :start_datetime, :class => "form-control" %>
				</div>

				<!-- <div class="form-group col-md-6">
					<%= f.label :end_datetime, 'Ngày kết thúc:' %>
					<%= f.date_field :end_datetime, :class => "form-control" %>
				</div> -->
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :description, 'Description:' %>
					<%= f.text_area :description, :rows => 8, :class => "form-control", :placeholder => "Description" %>
				</div>
			</div>

			<%= f.hidden_field :del_flag, value: 0 %>

			<div class="row">
				<div class="form-group text-center">
					<%= f.submit 'Save', class: 'btn btn-danger' %>
					<%= submit_tag('Reset', {:name => 'reset', :type => 'reset', :id => 'reset_new_project', :class => 'btn btn-default'}) %>
				</div>
			</div>
		<% end %>
	</div>
</div>

employees_management/app/views/projects/show.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Leave days manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">Information project</span></li>
</ol>

<div class="panel panel-info">
	<div class="panel-heading">Information</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-12">
				<%= link_to '<i class="fa fa-suitcase"></i>'.html_safe, projects_path, :class => "btn btn-primary", :title => "List of projects" %>
				<%= link_to '<i class="fa fa-users"></i>'.html_safe, members_path, :class => "btn btn-danger", :title => "List of members" %>
				<div class="table-responsive">			
					<table class="table table-bordered table-hover" style="margin-top: 15px;">
						<thead style="background: #53585a; color: #fff;">
							<th width="20%"></th>
							<th width="80%" class="text-center">Information</th>
						</thead>
						<tbody>
							<tr>
								<td>Project name</td>
								<td><b><%= @project.project_name %></b></td>
							</tr>
							<tr>
								<td>Leader</td>
								<td><b>
									<% @leader.each do |l| %>
										<%= l.fullname %>
									<% end %>
								</b></td>
							</tr>
							<tr>
								<td>Members</td>
								<td><b>
									<% @members.each do |m| %>
											&#9679; <%= m.fullname %> <br>
									<% end %>	
								</b></td>
							</tr>
							<tr>
								<td>Project status</td>
								<td><b><%= @project.project_status %></b></td>
							</tr>
							<tr>
								<td>Language</td>
								<td><b><%= @project.project_lang %></b></td>
							</tr>
							<tr>
								<td>Start datetime</td>
								<td><b><%= @project.start_datetime %></b></td>
							</tr>
							<tr>
								<td>End datetime</td>
								<td><b><%= @project.end_datetime %></b></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>