employees_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes employees
  resources :employees

  # Routes leave days
  get '/all_leavedays', to: 'employees#all_leavedays'
  post '/all_leavedays', to: 'employees#update_leavedays'
  resources :leavedays

  # Routes projects
  resources :projects

  # Routes ots
  resources :ots

  # Routes members
  resources :members 

  root 'employees#index'

end

employees_management/app/models/employee.rb
class Employee < ApplicationRecord
    has_and_belongs_to_many :projects
    has_many :leavedays
    has_many :ots
    has_many :members

	# name: Độc nhất, không bỏ trống, tối thiểu 5 ký tự, tối đa 255 ký tự
    validates :username, uniqueness: true, presence:true, length: {in: 5..255}
    validates :fullname, presence:true, length: {in: 5..255}

	# email: Không bỏ trống, tính duy nhất, đúng định dạng email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email_company, :email_personal, length: {in: 4..255}, presence: true, uniqueness: true , format: { with: VALID_EMAIL_REGEX, message: "not in correct format." }

    # validates :password, presence: true, length: {in: 6..55}
    # Use gem bcrypt
	# has_secure_password

	# Không bỏ trống
    validates :gender, :birthday, :department, :position, :contract_type, :status, :user_type, :join_datetime, :id_number, presence: true
    
    # Image: validate paperclip
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/ 
    # validates_attachment_content_type :image, :content_type => [/\Aimage/, 'application/octet-stream']
    # validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
    # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    # do_not_validate_attachment_file_type :image

    # validate :check_content_type    
    # def check_content_type
    #     if !['image/jpeg', 'image/gif','image/png', 'image/jpg'].include?(self.image_content_type)
    #         errors.add_to_base("File '#{self.image_file_name}' không đúng định dạng của hình ảnh.") # or errors.add
    #     end
    # end

    # validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
end

employees_management/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = if params[:fullname] || params[:email_company] || params[:birthday] || params[:gender] || params[:tel] || params[:department] || params[:position] || params[:user_type] || params[:status] || params[:join_datetime]
			Employee.select('id, username, fullname, email_company, tel, gender, birthday, department, position, status, join_datetime').where('fullname LIKE ? AND email_company LIKE ? AND birthday LIKE ? AND gender LIKE ? AND tel LIKE ? AND department LIKE ? AND position LIKE ? AND user_type LIKE ? AND status LIKE ? AND join_datetime LIKE ?', "%#{params[:fullname]}%", "%#{params[:email_company]}%", "%#{params[:birthday]}%", "%#{params[:gender]}%", "%#{params[:tel]}%", "%#{params[:department]}%", "%#{params[:position]}%", "%#{params[:user_type]}%", "%#{params[:status]}%", "%#{params[:join_datetime]}%").where(del_flag: 0).paginate(:page => params[:page], :per_page => 10).order('id DESC')
		else
			Employee.select('id, username, fullname, email_company, tel, gender, birthday, department, position, status, join_datetime').where(del_flag: 0).paginate(:page => params[:page], :per_page => 10).order('id DESC')
		end
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(employee_params)
		if (@employee.save)
			flash[:success] = "Add new employee success!"
			redirect_to employees_path
		else
			render 'new'
		end
	end

	def show
		@employee = Employee.find(params[:id])
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if (@employee.update(employee_params))
			flash[:success] = "Update success!"
			redirect_to employees_path
		else
			render 'edit'
		end
	end

	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		flash[:success] = 'Delete success!'
		redirect_to employees_path
	end

	def all_leavedays
		@employees = Employee.select('id', 'fullname', 'join_datetime', 'leavedays_have', 'leavedays_took', 'leavedays_note').where(del_flag: 0).paginate(:page => params[:page], :per_page => 10).order('id DESC')
	end

	def update_leavedays
		if !params[:leavedays_have].nil?
			Employee.update(params[:id], :leavedays_have => params[:leavedays_have])
		end

		if !params[:leavedays_took].nil?
			Employee.update(params[:id], :leavedays_took => params[:leavedays_took])
		end 

		if !params[:leavedays_note].nil?
			Employee.update(params[:id], :leavedays_note => params[:leavedays_note])
		end 
			
		flash[:success] = 'Edit success!'
		redirect_to all_leavedays_path
	end

	private def employee_params
		params.require(:employee).permit(:username, :fullname, :email_company, :email_personal, :tel, :gender, :birthday, :avatar, :department, :position, :skill, :user_type, :literacy, :contract_type, :status, :address, :bank_account, :id_number, :description, :join_datetime, :exit_datetime, :leavedays_have, :leavedays_took, :leavedays_note, :del_flag)
	end
end

employees_management/app/helpers/employees_helper.rb
module EmployeesHelper
end

employees_management/app/views/employees/edit.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Employees manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;"><%= @employee.fullname %></span></li>
</ol>

<% if @employee.errors.any? %>
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger">
				<% @employee.errors.full_messages.each do |msg| %>
						&#9679; <%= msg %> <br>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

<div class="panel panel-info">
	<div class="panel-heading">Edit information employee</div>
	<div class="panel-body">
		<%= form_for @employee, html: {mutipart: true} do |f| %>
			<div class="row">
				<div class="col-md-6 text-center">

					<div class="fileinput fileinput-new" data-provides="fileinput">
						<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
							<%= image_tag @employee.avatar.url, alt: "Avatar" %>
						</div>
						<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
						<div>
							<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :image %></span>
							<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
						</div>
					</div>

				</div>
				<div class="col-md-6">
					<div class="row">
						<div class="form-group col-md-12">
							<%= f.label :username, 'Username:  <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
							<%= f.text_field :username, :class => "form-control", :placeholder => "Username" %>
						</div>

						<div class="form-group col-md-12">
							<%= f.label :fullname, 'Fullname: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
							<%= f.text_field :fullname, :class => "form-control", :placeholder => "Fullname" %>
						</div>

						<div class="form-group col-md-12">
							<%= f.label :gender, 'Gender: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %> <br>
							<%= f.radio_button :gender, "1" %> Male
							<%= f.radio_button :gender, "2" %> Female
						</div>

						<div class="form-group col-md-12">
							<%= f.label :tel, "Telephone number:" %>
							<%= f.telephone_field :tel, :class => "form-control", :placeholder => "Tel" %>
						</div>
					</div>
				</div>
			</div>
			
			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :email_company, 'Email company: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.email_field :email_company, :class => "form-control", :placeholder => "Email company" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :email_personal, 'Email personal: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.email_field :email_personal, :class => "form-control", :placeholder => "Email personal" %>
				</div>
			</div>
			
			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :birthday, 'Birthday: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.date_field :birthday, :class => "form-control", :placeholder => "Birthday" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :department, 'Department: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :department, [['--- Select department ---', ''], 'App', 'Web', 'Difference'], {}, :class => "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :position, 'Position: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :position, [['--- Select position ---', ''], 'Director', 'Employee', 'Tester', 'Leader'], {}, :class => 'form-control' %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :skill, "Skill:" %>
					<%= f.text_field :skill, :class => "form-control", :placeholder => "Skill" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :literacy, "Literacy:" %>
					<%= f.text_field :literacy, :class => "form-control", :placeholder => "Literacy" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :contract_type, 'Contract type: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :contract_type, [['--- Select contract type ---', ''], '3 months', '6 months', '1 year', '2 years', '3 years', '5 years', 'Duration', 'Forever'], {}, :class => "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :status, 'Status: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :status, [['--- Select status ---', ''], 'Joining', 'Exited', 'Absent'], {}, :class => "form-control" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :user_type, 'Employee type: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.select :user_type, [['--- Select user type ---', ''], 'Offical', 'Internship', 'Probationary', 'Contract', 'Difference'], {}, :class => "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :join_datetime, 'Join datetime: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.date_field :join_datetime, :class => "form-control", :placeholder => "Join datetime" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :exit_datetime, "End datetime:" %>
					<%= f.date_field :exit_datetime, :class => "form-control", :placeholder => "Exit datetime" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :address, "Address:" %>
					<%= f.text_field :address, :class => "form-control", :placeholder => "Address" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-6">
					<%= f.label :bank_account, "Bank account:" %>
					<%= f.text_field :bank_account, :class => "form-control", :placeholder => "Bank account" %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :id_number, 'ID number: <span style="color:red;"><b>[<i class="fa fa-asterisk"></i>]</b></span>'.html_safe %>
					<%= f.text_field :id_number, :class => "form-control", :placeholder => "Id number" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group col-md-12">
					<%= f.label :description, "Description:" %>
					<%= f.text_area :description, :class => "form-control", :placeholder => "Description", rows: 10 %>
				</div>
			</div>

			<div class="row">
				<div class="form-group text-center">
					<%= f.submit "Save", class: "btn btn-danger" %>
					<%= link_to "Cancel", employee_path(@employee), :class => "btn btn-default" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

employees_management/app/views/employees/index.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Employees manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;">List of employees</span></li>
</ol>

<!-- Display notification -->
<% flash.each do |type, message| %>
	<%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= message %>
	<% end %>
<% end %>

<div class="panel panel-info">
	<div class="panel-heading">Search employee</div>
	<div class="panel-body">
		<%= form_tag(employees_path, method: :get) do %>
			<div class="row">
				<div class="form-group col-md-6">
					<%= label_tag :fullname, "Fullname:" %>
					<%= text_field_tag :fullname, params[:fullname], class: "form-control", placeholder: "Fullname" %>
				</div>
				<div class="form-group col-md-6">
					<%= label_tag :email_company, "Email company:" %>
					<%= email_field_tag :email_company, params[:email_company], class: "form-control", placeholder: "Email company" %>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-md-6">
					<%= label_tag :birthday, "Birthday:" %>
					<%= date_field_tag :birthday, params[:birthday], class: "form-control", placeholder: "Birthday" %>
				</div>
				<div class="form-group col-md-6">
					<%= label_tag :gender, "Gender:" %> <br>
					<%= radio_button_tag :gender, "1" %> Male
					<%= radio_button_tag :gender, "2" %> Female
				</div>
			</div>
			<div class="row">
				<div class="form-group col-md-6">
					<%= label_tag :tel, "Telephone number:" %>
					<%= telephone_field_tag :tel, params[:tel], class: "form-control", placeholder: "Tel" %>
				</div>
				<div class="form-group col-md-6">
					<%= label_tag :department, "Department:" %>
					<%= select_tag :department, options_for_select([['--- Select department ---', ''], 'App', 'Web', 'Difference']), {:class => "form-control"} %>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-md-6">
					<%= label_tag :position, "Position:" %>
					<%= select_tag :position, options_for_select([['--- Select position ---', ''], 'Director', 'Employee', 'Tester', 'Leader']), {:class => 'form-control'} %>
				</div>
				<div class="form-group col-md-6">
					<%= label_tag :user_type, "Employee type:" %>
					<%= select_tag :user_type, options_for_select([['--- Select employee type ---', ''], 'Offical', 'Internship', 'Probationary', 'Contract', 'Difference']), {:class => "form-control"} %>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-md-6">
					<%= label_tag :status, "Status:" %>
					<%= select_tag :status, options_for_select([['--- Select status ---', ''], 'Joining', 'Exited', 'Absent']), {:class => "form-control"} %>
				</div>
				<div class="form-group col-md-6">
					<%= label_tag :join_datetime, "Join datetime:" %>
					<%= date_field_tag :join_datetime, params[:join_datetime], :class => "form-control", :placeholder => "Join datetime" %>
				</div>
			</div> 
			<div class="row">
				<div class="form-group text-center">
					<%= submit_tag('Reset', {:name => 'reset', :id => 'reset_button', :type => 'reset', :class => 'btn btn-primary'}) %>
					<%= submit_tag 'Search', class: 'btn btn-danger' %>
				</div>
			</div>
		<% end %>
	</div>
</div>

<div class="panel panel-info">
	<div class="panel-heading">List of employees</div>
	<div class="panel-body">
		<%= link_to '<i class="fa fa-refresh"></i> Reload'.html_safe, employees_path, :class => "btn btn-default" %>
		<div class="table-responsive">			
			<table class="table table-bordered table-hover" style="margin-top: 15px; font-size: 11px;">
				<thead style="background: #53585a; color: #fff;">
					<th>No.</th>
					<th>Username</th>
					<th width="15%">Fullname</th>
					<th>Email company</th>
					<th>Telephone</th>
					<th>Gender</th>
					<th>Birthday</th>
					<th>Department</th>
					<th>Position</th>
					<th>Status</th>
					<th>Join datetime</th>
					<th>Detail</th>
					<th>Delete</th>
				</thead>
				<tbody>

					<% if @employees.empty? %>
						<tr>
							<td colspan="13" class="text-center" style="color:red;"><i class="fa fa-exclamation-triangle"></i> Not data</td>
						</tr>
					<% else %>
						<!-- Loop Each -->
						<% i = 1 %>
						<% @employees.each do |employee| %>
							<tr>
								<td class="text-center"><%= i %></td>
								<td><%= employee.username %></td>
								<td><%= employee.fullname %></td>
								<td><%= employee.email_company %></td>
								<td><%= employee.tel %></td>
								<td><%= employee.gender == 1 ? 'Male' : 'Female' %></td>
								<td><%= employee.birthday %></td>
								<td><%= employee.department %></td>
								<td><%= employee.position %></td>
								<td><%= employee.status %></td>
								<td><%= employee.join_datetime %></td>
								<td><%= link_to '<i class="fa fa-info-circle"></i>'.html_safe, employee_path(employee), :class => "btn btn-sm btn-primary" %></td>
								<td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, employee_path(employee), :class => "btn btn-sm btn-danger", method: :delete, :data => {:confirm => "Are you sure?"} %></td>
							</tr>
							<% i += 1 %>
						<% end %>
					<% end %>

				</tbody>
			</table>
		</div>

		<!-- Pagination -->
		<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
	</div>
</div>	

employees_management/app/views/employees/show.html.erb
<ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
	<li class="breadcrumb-item"><a href="#"><i class="fa fa-user"></i> Employees manage</a></li>
	<li class="breadcrumb-item active"><span style="color: red;"><%= @employee.fullname %></span></li>
</ol>
<div class="panel panel-info">
	<div class="panel-heading">Information</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4 text-center">
				<!-- Khi chưa có ảnh thì lấy mặc định ảnh missing.png trong public/images/original -->
				<%= image_tag(@employee.avatar.url(:medium), :class => "img-thumbnail", size: "200x200", alt: "Avatar") %>
			</div>
			<div class="col-md-8">
				<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_employee_path(@employee), :class => "btn btn-sm btn-primary", 'data-toggle' => 'tooltip', :title => "Edit" %>
				<%= link_to '<i class="fa fa-trash"></i>'.html_safe, employee_path(@employee), :class => "btn btn-sm btn-danger", method: :delete, :data => {:confirm => "Are you sure?"}, 'data-toggle' => 'tooltip', :title => "Delete" %>
				
				<table class="table table-bordered table-hover" style="margin-top: 10px;">
					<thead style="background: #53585a; color: #fff;">
						<th width="30%"></th>
						<th width="70%" class="text-center">Information</th>
					</thead>
					<tbody>
						<tr>
							<td>Username</td>
							<td><b><%= @employee.username %></b></td>
						</tr>
						<tr>
							<td>Fullname</td>
							<td><b><%= @employee.fullname %></b></td>
						</tr>
						<tr>
							<td>Email company</td>
							<td><b><%= @employee.email_company %></b></td>
						</tr>
						<tr>
							<td>Email personal</td>
							<td><b><%= @employee.email_personal %></b></td>
						</tr>
						<tr>
							<td>Telephone number</td>
							<td><b><%= @employee.tel %></b></td>
						</tr>
						<tr>
							<td>Gender</td>
							<td><b><%= @employee.gender == 1 ? "Male" : "Female" %></b></td>
						</tr>
						<tr>
							<td>Birthday</td>
							<td><b><%= @employee.birthday %></b></td>
						</tr>
						<tr>
							<td>Department</td>
							<td><b><%= @employee.department %></b></td>
						</tr>
						<tr>
							<td>Position</td>
							<td><b><%= @employee.position %></b></td>
						</tr>
						<tr>
							<td>Employee type</td>
							<td><b><%= @employee.user_type %></b></td>
						</tr>
						<tr>
							<td>Skill</td>
							<td><b><%= @employee.skill %></b></td>
						</tr>
						<tr>
							<td>Literacy</td>
							<td><b><%= @employee.literacy %></b></td>
						</tr>
						<tr>
							<td>Contract type</td>
							<td><b><%= @employee.contract_type %></b></td>
						</tr>
						<tr>
							<td>Status</td>
							<td><b><%= @employee.status %></b></td>
						</tr>
						<tr>
							<td>Address</td>
							<td><b><%= @employee.address %></b></td>
						</tr>
						<tr>
							<td>Bank account</td>
							<td><b><%= @employee.bank_account %></b></td>
						</tr>
						<tr>
							<td>ID number</td>
							<td><b><%= @employee.id_number %></b></td>
						</tr>
						<tr>
							<td>Join datetime</td>
							<td><b><%= @employee.join_datetime %></b></td>
						</tr>
						<tr>
							<td>End datetime</td>
							<td><b><%= @employee.exit_datetime %></b></td>
						</tr>
						<tr>
							<td>Description</td>
							<td><b><%= @employee.description %></b></td>
						</tr>
						
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>